name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Lazarus
        uses: gcarreno/setup-lazarus@v3
        with:
          lazarus-version: stable
          with-cache: true

      - name: Build with Lazarus
        run: |
          lazbuild src/standard/pasls.lpi
          
      - name: Upload Pascal Language Server
        uses: actions/upload-artifact@v3
        with:
          name: Pascal_Language_Server
          path: |
            *
          retention-days: 60
